# Generated by Django 3.1.7 on 2021-04-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_auto_20210408_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contactno',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
