# Generated by Django 3.1.7 on 2021-04-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0008_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_first_name', models.CharField(max_length=30)),
                ('tutor_last_name', models.CharField(max_length=30)),
                ('tutor_username', models.CharField(max_length=30)),
                ('tutor_password', models.CharField(max_length=30)),
                ('tutor_address', models.CharField(max_length=30)),
                ('tutor_gender', models.CharField(max_length=30)),
                ('tutor_contactno', models.IntegerField(default=0)),
                ('tutor_emailaddress', models.CharField(max_length=30, unique=True)),
                ('tutor_qualification', models.CharField(max_length=30)),
                ('tutor_educationalInstitute', models.CharField(max_length=30)),
                ('tutor_chargePerHour', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='chargePerHour',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
