# Generated by Django 3.1.7 on 2021-04-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0009_auto_20210411_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='educationalInstitute',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
