# Generated by Django 3.1.7 on 2021-04-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0010_user_educationalinstitute'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academicleveltoteach',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='academicLevel',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
