# Generated by Django 3.1.7 on 2021-04-12 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0013_bill_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='session_time',
            field=models.TimeField(default=datetime.time(13, 59, 7, 471138)),
        ),
    ]
