# Generated by Django 3.1.7 on 2021-04-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0014_auto_20210412_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='message',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='session_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='session_time',
            field=models.CharField(max_length=40),
        ),
    ]
