# Generated by Django 3.2 on 2021-04-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0017_alter_sessions_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='session_days',
            field=models.IntegerField(default=0),
        ),
    ]
