# Generated by Django 3.2 on 2021-04-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0018_sessions_session_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='message',
            field=models.CharField(default='', max_length=100),
        ),
    ]
