# Generated by Django 3.2 on 2021-04-20 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0020_auto_20210418_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessions',
            old_name='session_time',
            new_name='session_enddate',
        ),
    ]
