# Generated by Django 3.1.7 on 2021-04-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0023_auto_20210422_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfile',
            name='message',
            field=models.CharField(default='', max_length=255),
        ),
    ]
