# Generated by Django 3.2 on 2021-04-22 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0026_alter_notification_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recepient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
    ]
