# Generated by Django 3.1.7 on 2021-04-23 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0027_alter_notification_recepient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='seession',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tutor.sessions'),
        ),
    ]
