# Generated by Django 3.1.7 on 2021-04-23 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0029_auto_20210423_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='seession',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tutor.sessions'),
        ),
    ]
