# Generated by Django 3.1.7 on 2021-04-23 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0030_auto_20210423_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='seession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutor.sessions'),
        ),
    ]
